image:
  repository: sigp/lighthouse
  tag: latest
  pullPolicy: IfNotPresent

container:
  command:
    - lighthouse
    - beacon_node
  args:
    - --datadir
    - /data
    - --debug-level
    - info
    - --testnet
    - medalla
    - --http
    - --http-address
    - "0.0.0.0"
    - --ws
    - --ws-address
    - "0.0.0.0"
    - --metrics
    - --metrics-address
    - "0.0.0.0"
    - --eth1-endpoint
    - https://cloudflare-eth.com

ports:
  http: 5052
  metrics: 5054
  discovery: 9000

storage:
  capacity: 20Gi

resources:
  requests:
    cpu: 250m
    memory: 2Gi
  limits:
    cpu: 500m
    memory: 3Gi

affinity: {}