image:
  repository: sigp/lighthouse
  tag: stable
  pullPolicy: IfNotPresent

container:
  command:
    - lighthouse
    - beacon_node
  args:
    - --datadir
    - /data
    - --debug-level
    - info
    - --network
    - pyrmont
    - --http
    - --http-address
    - "0.0.0.0"
    - --ws
    - --ws-address
    - "0.0.0.0"
    - --metrics
    - --metrics-address
    - "0.0.0.0"
    - --eth1-endpoint
    - https://cloudflare-eth.com

ports:
  http: 5052
  metrics: 5054
  discovery: 9000

storage:
  capacity: 20Gi

livenessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds: 10

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # requests:
  #   cpu: 250m
  #   memory: 2Gi
  # limits:
  #   cpu: 500m
  #   memory: 3Gi

affinity: {}

servicemonitor:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}