enabled: true

image:
  repository: sigp/lighthouse
  tag: stable

container:
  command:
    - lighthouse
    - validator
  args:
    - --datadir
    - /data
    - --debug-level
    - info
    - --disable-auto-discover
    - --network
    - pyrmont
    - --beacon-node
    - http://lighthouse-beacon:5052
    - --graffiti
    - Lighthouse Validator

# A list of secrets and their paths to mount inside the pod
# keystore secret containing keystore.json
# definitions secrets containing validator_definitions.yml
# These will be copied by initContainer from /data/mount to /data/validators
secretMounts: []
#  - name: keystore
#    secretName: keystore
#    path: /data/mount/0x0000
#  - name: definitions
#    secretName: definitions
#    path: /data/mount

ports:
  metrics: 5064

storage:
  capacity: 1Gi

livenessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 30
  failureThreshold: 5
  periodSeconds: 10

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # requests:
  #   cpu: 100m
  #   memory: 256Mi
  # limits:
  #   cpu: 200m
  #   memory: 512Mi

service:
  enabled: true
  type: ClusterIP

servicemonitor:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}