apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "lighthouse-beacon-node.fullname" . }}-data
  labels:
    {{- include "lighthouse-beacon-node.labels" . | nindent 4 }}
    type: local
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.storage.capacity | quote }}
  hostPath:
    path: /data