apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lighthouse-validator.fullname" . }}
  labels:
    {{- include "lighthouse-validator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lighthouse-validator.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "lighthouse-validator.fullname" . }}  
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "lighthouse-validator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          lifecycle:
            postStart:
              exec:
                command:
                - /bin/sh
                - -c
                - cp -rL /data/mount /data/validators
          {{- if .Values.container.command }}
          command:
{{ toYaml .Values.container.command | indent 12 }}
          {{- end }}
          {{- if .Values.container.args }}
          args:
{{ toYaml .Values.container.args | indent 12 }}
          {{- end }}
          resources: 
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /node/health
              port: {{ .Values.ports.metrics }}
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: validator-data
              mountPath: /data
            {{- range .Values.secretMounts }}
            - name: {{ .name }}
              mountPath: {{ .path }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.ports.metrics }}
      volumes:
        {{- range .Values.secretMounts }}
          - name: {{ .name }}
            secret:
              secretName: {{ .secretName }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: validator-data
      spec:
        storageClassName: manual
        accessModes: 
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.storage.capacity | quote }}