apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse-validator.fullname" . }}
  labels:
    {{- include "lighthouse-validator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "lighthouse-validator.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ (index .Values "config" "p2p-tcp-port") | default 13000 }}
      name: p2p-tcp
    - protocol: UDP
      port: {{ (index .Values "config" "p2p-udp-port") | default 12000 }}
      name: p2p-udp
    - protocol: TCP
      port: {{ (index .Values "config" "monitoring-port") | default 8080 }}
      name: monitoring