apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lighthouse-beacon.fullname" . }}
  labels:
    {{- include "lighthouse-beacon.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lighthouse-beacon.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "lighthouse-beacon.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "lighthouse-beacon.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.container.command }}
          command:
{{ toYaml .Values.container.command | indent 12 }}
          {{- end }}
          {{- if .Values.container.args }}
          args:
{{ toYaml .Values.container.args | indent 12 }}
          {{- end }}
          resources: 
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /node/health
              port: {{ .Values.ports.metrics }}
            failureThreshold: 60
            initialDelaySeconds: 600
            periodSeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /node/health
              port: {{ .Values.ports.metrics }}
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: beacon-data
              mountPath: /data
            {{- if .Values.config }}
            - name: beacon-config
              mountPath: /data/config
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.ports.metrics }}
            - name: discovery
              containerPort: {{ .Values.ports.discovery  }}
            - name: websocket
              containerPort: {{ .Values.ports.websocket }}
      volumes:
        {{- if .Values.config }}
        - name: beacon-config
          configMap:
            name: beacon-config
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: beacon-data
      spec:
        storageClassName: manual
        accessModes: 
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.storage.capacity | quote }}