{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse-beacon.fullname" . }}
  labels:
    {{- include "lighthouse-beacon.labels" . | nindent 4 }}
    app: {{ template "lighthouse-beacon.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "lighthouse-beacon.selectorLabels" . | nindent 4 }}
  ports:
    - name: discovery-udp
      port: {{ .Values.ports.discovery  }}
      protocol: UDP
    {{- range $key, $val := .Values.ports }}
    - name: {{ $key }}
      port: {{ $val }}
      protocol: TCP
    {{- end }}
{{- end -}}
